# Generated by Django 2.2.7 on 2020-01-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_account_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='connect_to_products',
        ),
        migrations.AlterField(
            model_name='client',
            name='connect_to_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Branch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='connect_to_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Client'),
        ),
    ]
